(() => {
'use strict';
const CFG=window.MR_CONFIG,U=CFG.universe,CHUNK=CFG.chunkSize,$=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const fmt=n=>new Intl.NumberFormat('en-US').format(Math.round(Number(n)||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(3,'0');
let C=null,catalogPromise=null,busy=false,currentResult=null,toastTimer=null;
const chunkCache=new Map(),loadingChunks=new Map(),detailShardPromises=new Map();
window.MR_OEIS_DETAILS_SHARDS=window.MR_OEIS_DETAILS_SHARDS||{};

function loadScript(src,test){return new Promise((resolve,reject)=>{if(test&&test())return resolve();const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error(`Could not load ${src}.`));document.head.appendChild(s)})}
function loadCatalog(){if(C)return Promise.resolve(C);if(catalogPromise)return catalogPromise;catalogPromise=loadScript('data/catalog.js',()=>!!window.MR_CATALOG).then(()=>C=window.MR_CATALOG);return catalogPromise}
function detailShard(aid){return Number(aid.slice(1))%16}
function loadDetailShard(sh){if(window.MR_OEIS_DETAILS_SHARDS[sh])return Promise.resolve();if(detailShardPromises.has(sh))return detailShardPromises.get(sh);const p=loadScript(`data/oeis/details_${String(sh).padStart(2,'0')}.js`,()=>!!window.MR_OEIS_DETAILS_SHARDS[sh]).catch(e=>console.warn(e));detailShardPromises.set(sh,p);return p}
async function loadDetailsForIds(ids){await loadCatalog();const shards=new Set();for(const id of ids){const r=C[id];if(r&&r[6])shards.add(detailShard(r[6]))}await Promise.all([...shards].map(loadDetailShard))}
function getDetail(aid){if(!aid)return null;return window.MR_OEIS_DETAILS_SHARDS[detailShard(aid)]?.[aid]||null}

// v8 chunk format: uint16 OEIS degree, uint8 id-count, uint16 badge ids. Score/rank are computed live.
function parseChunk(ci,b64){const bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);const dv=new DataView(a.buffer),rows=new Array(Math.min(CHUNK,U-ci*CHUNK));let o=0;for(let j=0;j<rows.length;j++){const degree=dv.getUint16(o,true);o+=2;const k=dv.getUint8(o);o++;const ids=new Array(k);for(let q=0;q<k;q++){ids[q]=dv.getUint16(o,true);o+=2}rows[j]={degree,ids}}chunkCache.set(ci,rows);return rows}
function loadChunk(ci){if(chunkCache.has(ci))return Promise.resolve(chunkCache.get(ci));if(loadingChunks.has(ci))return loadingChunks.get(ci);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`data/chunks/chunk_${pad(ci)}.js`;s.async=true;s.onload=()=>{try{const raw=window.MR_CHUNKS?.[ci];if(!raw)throw new Error('Missing number-data chunk.');resolve(parseChunk(ci,raw));delete window.MR_CHUNKS[ci];s.remove()}catch(e){reject(e)}};s.onerror=()=>reject(new Error('Could not load this number-data chunk.'));document.head.appendChild(s)}).finally(()=>loadingChunks.delete(ci));loadingChunks.set(ci,p);return p}
async function getNumber(n){const ci=Math.floor(n/CHUNK),rows=await loadChunk(ci);return rows[n-ci*CHUNK]}

function chanceText(p){p=Number(p)||0;if(p<=0)return'Extremely rare';if(p>=.01)return`${(p*100).toFixed(p>=.1?1:2)}% chance`;return`1 in ${fmt(Math.max(1,Math.round(1/p)))}`}
function infoBase(bits){return bits>0?20*(Math.pow(2,bits/2)-1):0}
function scoreBalanceMultiplier(row){const cfg=CFG.scoreBalance;if(!cfg)return 1;const bits=Math.max(0,Number(row?.[4])||0),lo=Number(cfg.startBits)||3,hi=Math.max(lo+.01,Number(cfg.fullAtBits)||9.5),floor=Math.max(0,Math.min(1,Number(cfg.floor)||.67)),ceiling=Math.max(floor,Math.min(1.25,Number(cfg.ceiling)||1));let t=Math.max(0,Math.min(1,(bits-lo)/(hi-lo)));t=t*t*(3-2*t);return floor+(ceiling-floor)*t}
// v11 beauty balance: representation-dependent coincidences are intentionally compressed,
// while invariant number-theoretic/algebraic/combinatorial structure gets a modest lift.
function beautyProfile(row){const src=String(row?.[0]||''),f=String(row?.[10]||''),cat=String(row?.[5]||'').toLowerCase(),ds=(row?.[13]||[]).join(' ').toLowerCase(),text=`${f} ${cat} ${ds}`;const representation=/digit|decimal|binary|cross_base|base\d|base_|palindrom|repdigit|pandigital|harshad|zuckerman|keith|kaprekar|automorphic|trimorphic|reverse/.test(text);const artificial=/digit_patterns|digit_structure|digit_sequences|cross_base|arithmetic_coincidence|residue_patterns/.test(text);const pure=/prime_factor|divisib|abundan|perfect_number|pseudoprime|prime_structure|classical_number_theory|algebra|finite_field|modular|totient|mobius|carmichael|diophant|figurate|geometry|projective|grassmann|lie_|root_system|combinator|partition|analysis_qseries|topology|arithmetic_special|sequences/.test(text);let mult=1,cap=Infinity;if(representation){mult=.48;cap=1500000;if(src==='x')mult=.55;if(/multi_base_harshad/.test(f)){mult=.62;cap=1800000}else if(/polydivisible|alternating_sum|equal_frequency|no_adjacent|same_digit_sum|sum_product|antipalindrome/.test(f)){mult=.40;cap=1200000}else if(/palindrome|repdigit/.test(f)){mult=.50;cap=1500000}}else if(artificial){mult=.68;cap=2500000}else if(pure||/factor_pattern/.test(text)){mult=1.18;if(/algebraic_number_theory|finite_fields|prime_factorization|pseudoprime|diophantine|arithmetic_special/.test(text))mult=1.23}else if(src==='g')mult=1.02;
// Parameter values are witness detail, not a license to turn a good family into dozens of pseudo-unique jackpots.
// Preserve a strong reward for the structure itself while capping rarity created only by the exact parameter.
if(f==='factor_primes_ap'||f==='factor_exponents_ap')cap=Math.min(cap,4000000);if(f==='abelian_group_count')cap=Math.min(cap,5000000);return{mult,cap}}
function badgeEP(row,degree,n){let base=Number(row[8])||0,weight=row[14]==null?1:Number(row[14]);if(row[0]==='g'){const I=Number(row[4])||0,J=Math.log2(CFG.oeisCatalogueSize/Math.max(1,degree));base=infoBase(Math.sqrt(Math.max(0,I*J)))}const x=Math.max(0,base*Math.max(0,weight));let ep=x?Math.round(CFG.scoreLaw.a*Math.pow(x,CFG.scoreLaw.b)):0;if(row[0]==='g'||row[0]==='c'){if(n<CFG.oeisPolicy.minimumNumber)return 0;if(n>=100000)ep*=CFG.oeisPolicy.sixDigitMultiplier;else if(n>=10000)ep*=CFG.oeisPolicy.fiveDigitMultiplier}if(row[0]==='x')ep=Math.round(ep*(CFG.specialEventMultiplier||1));ep=Math.round(ep*scoreBalanceMultiplier(row));const bp=beautyProfile(row);ep=Math.min(bp.cap,Math.round(ep*bp.mult));return ep}
function badgeInfo(id,degree,n){const r=C[id];if(!r)return null;return{id,row:r,src:r[0],name:r[1],emoji:r[2],p:Number(r[3])||0,bits:Number(r[4])||0,cat:r[5],oeis:r[6],base:Number(r[8])||0,rarity:r[9]||'Common',family:r[10]||'',variant:String(r[11]??''),explain:(r[12]||''),domains:r[13]||[],weight:Number(r[14])||1,detail:getDetail(r[6]),ep:badgeEP(r,degree,n)}}
const baseFam=new Set(['base_all_distinct','base_alt_parity','base_arithmetic_digits','base_equal_frequency','base_palindrome','base_product_square','base_strict_monotone','base_sum_prime','base_sum_square','base_sum_triangular']);
function baseFromBadge(b){if(b.src==='v'&&baseFam.has(b.family))return Number(b.variant)||null;const m=b.family.match(/^base(\d+)_(palindrome|repdigit|all_digits_distinct|all_digits_equal_frequency|happy|monotone_digits|alternating_digits)$/);return m?Number(m[1]):null}
const groupNames={base_all_distinct:'Distinct digits across bases',base_alt_parity:'Alternating digit parity across bases',base_arithmetic_digits:'Arithmetic-progression digits across bases',base_equal_frequency:'Equal digit frequencies across bases',base_palindrome:'Palindromic across bases',base_product_square:'Square digit product across bases',base_strict_monotone:'Strictly monotone digits across bases',base_sum_prime:'Prime digit sum across bases',base_sum_square:'Square digit sum across bases',base_sum_triangular:'Triangular digit sum across bases',base_repdigit:'Repdigits across bases',base_all_digits_distinct:'Distinct digits across bases',base_happy:'Happy in multiple bases',base_monotone_digits:'Monotone expansions across bases',base_alternating_digits:'Alternating expansions across bases'};
const exactConceptByFamily={fibonacci_value:'A000045',involution_value:'A000085',catalan_value:'A000108',bell_value:'A000110',pell_value:'A000129',pell_lucas_value:'A001333',factorial_value:'A000142',lucas_value:'A000204',plane_partition_value:'A000219',mersenne_number:'A000225',mersenne_prime_value:'A000225',euler_secant_value:'A000364',perfect_fourth:'A000583',central_binomial_value:'A000984',little_schroeder_value:'A001003',motzkin_value:'A001006',jacobsthal_value:'A001045',primorial_value:'A002110',woodall_number:'A003261',large_schroeder_value:'A006318',tribonacci_value:'A000073',markov_number:'A002559'};
const conceptByOEIS=Object.fromEntries(Object.entries(exactConceptByFamily).map(([f,a])=>[a,f]));
const aggregateBaseFamily={multi_base_palindrome:'base_palindrome',multi_base_equal_frequency:'base_equal_frequency',multi_base_arithmetic_digits:'base_arithmetic_digits',palindrome_in_two_bases:'base_palindrome',alternating_parity_in_three_bases:'base_alt_parity'};
const aggregateFamilies=new Set(['cross_base_same_digit_sum','multi_base_alternating_sum','multi_base_antipalindrome','multi_base_arithmetic_digits','multi_base_balanced_halves','multi_base_equal_frequency','multi_base_harshad','multi_base_no_adjacent_repeat','multi_base_palindrome','multi_base_pandigital','multi_base_polydivisible','multi_base_sum_product']);
let _factsN=-1,_factsCache=new Map();
function baseFacts(n,b){if(_factsN!==n){_factsN=n;_factsCache=new Map()}if(_factsCache.has(b))return _factsCache.get(b);const r=toBase(n,b),a=digitsOf(r),L=a.length,m=new Map();for(const x of a)m.set(x,(m.get(x)||0)+1);const counts=[...m.values()],palindrome=L>=3&&r===[...r].reverse().join(''),allDistinct=m.size===L,equalRaw=L>=4&&m.size>=2&&counts.every(x=>x===counts[0]),d=a.slice(1).map((x,i)=>x-a[i]),arithmetic=L>=3&&d.length&&d[0]!==0&&d.every(x=>x===d[0]),strictMonotone=L>=3&&(a.slice(1).every((x,i)=>x>a[i])||a.slice(1).every((x,i)=>x<a[i])),noAdjacentRaw=L>=4&&a.slice(1).every((x,i)=>x!==a[i]),h=L/2,balancedRaw=L>=4&&L%2===0&&a.slice(0,h).reduce((x,y)=>x+y,0)===a.slice(h).reduce((x,y)=>x+y,0),altA=a.filter((_,i)=>i%2===0).reduce((q,y)=>q+y,0),altB=a.filter((_,i)=>i%2).reduce((q,y)=>q+y,0),alternatingRaw=L>=4&&altA===altB,z=[...m.keys()].sort((x,y)=>x-y),pandigital=L>=b&&z.length===b&&z.every((x,i)=>x===i),f={r,a,L,palindrome,repdigit:L>=2&&m.size===1,allDistinct,equalFrequency:equalRaw&&!allDistinct,arithmetic,strictMonotone,noAdjacent:noAdjacentRaw&&!allDistinct,balancedHalves:balancedRaw&&!palindrome,alternatingSum:alternatingRaw&&!(palindrome&&L%2===0),pandigital};_factsCache.set(b,f);return f}
function aggregateBaseCount(f,n){if(f==='cross_base_same_digit_sum'){const m=new Map();for(let b=2;b<=10;b++){const zf=baseFacts(n,b);if(zf.L<3)continue;const z=digitSum(zf.r);m.set(z,(m.get(z)||0)+1)}return Math.max(0,...m.values())}let c=0;for(let b=2;b<=10;b++){const zf=baseFacts(n,b),{r,a,L}=zf;let ok=false;if(f==='multi_base_palindrome')ok=zf.palindrome&&!zf.repdigit;else if(f==='multi_base_equal_frequency')ok=zf.equalFrequency;else if(f==='multi_base_arithmetic_digits')ok=zf.arithmetic;else if(f==='multi_base_balanced_halves')ok=zf.balancedHalves;else if(f==='multi_base_harshad'){const z=a.reduce((x,y)=>x+y,0);ok=L>=3&&z>1&&n%z===0}else if(f==='multi_base_no_adjacent_repeat')ok=zf.noAdjacent;else if(f==='multi_base_polydivisible')ok=L>=4&&a.every((_,i)=>parseInt(r.slice(0,i+1),b)%(i+1)===0);else if(f==='multi_base_sum_product'){const z=a.reduce((x,y)=>x+y,0),q=a.reduce((x,y)=>x*y,1);ok=L>=3&&q>0&&z===q}else if(f==='multi_base_alternating_sum')ok=zf.alternatingSum;else if(f==='multi_base_antipalindrome')ok=L>=4&&a.every((x,i)=>x+a[L-1-i]===b-1);else if(f==='multi_base_pandigital')ok=zf.pandigital;if(ok)c++}return c}
function semanticKey(b){
 if(b.family==='abundance'&&b.variant==='perfect')return'EXACT:perfect_number';if(b.oeis==='A000396')return'EXACT:perfect_number';
 if(b.family==='n_times_reverse_square'||b.family==='dec_reverse_product_square')return'EXACT:reverse_product_square';
 if(b.family==='n_plus_reverse_square'||b.family==='dec_reverse_sum_square')return'EXACT:reverse_sum_square';
 if(b.family==='repeat_halves'||(b.family==='dec_repeating_block'&&b.variant==='3'))return'EXACT:repeat_halves';
 if(b.family==='base2_repdigit')return'EXACT:A000225';
 if(b.family==='base10_repdigit'||(b.family==='dec_repeating_block'&&b.variant==='1'))return'EXACT:decimal_repdigit';
 if(b.family==='base2_alternating_digits'||(b.family==='base_alt_parity'&&b.variant==='2'))return'EXACT:base2_alternation';
 if(b.family==='omega_distinct')return`EXACT:omega:${b.variant}`;
 if(b.family==='primitive_idempotents'){const q=Number(b.variant);if(q>0&&(q&(q-1))===0)return`EXACT:omega:${Math.log2(q)}`}
 if(exactConceptByFamily[b.family])return'EXACT:'+exactConceptByFamily[b.family];if(conceptByOEIS[b.oeis])return'EXACT:'+b.oeis;return''}
function badgeValid(b,n){
 if(aggregateFamilies.has(b.family)){const need=Number(b.variant);if(Number.isFinite(need)&&need>0&&aggregateBaseCount(b.family,n)<need)return false}
 const base=baseFromBadge(b);if(base){const f=baseFacts(n,base);if(b.family==='base_equal_frequency'||/_all_digits_equal_frequency$/.test(b.family)){if(!f.equalFrequency)return false}}
 if((b.family==='dec_square_digit_sum_square'||b.family==='dec_cube_digit_sum_cube')&&String(n).split('').filter(x=>x!=='0').length<=1)return false;if(b.family==='dec_symmetric_pair_product_constant'&&b.variant==='0')return false;
 if(b.family==='base10_narcissistic'&&n<10)return false;
 if(b.family==='dec_equal_frequency_used'){const z=String(n),m=new Map();for(const c of z)m.set(c,(m.get(c)||0)+1);const q=[...m.values()];if(m.size<2||m.size===z.length||!q.every(x=>x===q[0]))return false}
 if(b.family==='dec_split_same_digit_product'){const z=String(n),pd=x=>[...x].reduce((a,c)=>a*Number(c),1);let ok=false;for(let i=1;i<z.length;i++){const a=pd(z.slice(0,i)),c=pd(z.slice(i));if(a>0&&a===c){ok=true;break}}if(!ok)return false}
 // Arithmetic-progressions need at least three data points; one/two-point APs are tautological.
 if(b.family==='factor_primes_ap'&&factorize(n).length<3)return false;
 if(b.family==='factor_exponents_ap'&&factorize(n).length<3)return false;
 if(b.family==='factor_exponents_palindrome'&&factorize(n).length<2)return false;
 if(b.family==='binary_one_positions_ap'){const ones=[...toBase(n,2)].filter(c=>c==='1').length;if(ones<3)return false}
 // Re-check representation length for generic/specialized base-pattern badges so old chunk hits cannot re-introduce trivial one/two-digit truths.
 if(base){const f=baseFacts(n,base);if(b.family==='base_palindrome'&&!f.palindrome)return false;if(b.family==='base_arithmetic_digits'&&!f.arithmetic)return false;if(b.family==='base_strict_monotone'&&!f.strictMonotone)return false;if(b.family==='base_all_distinct'&&(f.L<3||!f.allDistinct))return false;if(b.family==='base_alt_parity'){if(f.L<4||!f.a.slice(1).every((x,i)=>(x&1)!==(f.a[i]&1)))return false}if(b.family==='base_product_square'){const q=f.a.reduce((x,y)=>x*y,1);if(f.L<2||q<=0||Math.floor(Math.sqrt(q))**2!==q)return false}if(['base_sum_prime','base_sum_square','base_sum_triangular'].includes(b.family)&&f.L<2)return false;if(/_palindrome$/.test(b.family)&&/^base\d+_/.test(b.family)&&!f.palindrome)return false;if(/_repdigit$/.test(b.family)&&/^base\d+_/.test(b.family)&&!f.repdigit)return false;if(/_all_digits_distinct$/.test(b.family)&&f.L<3)return false;if(/_monotone_digits$/.test(b.family)&&f.L<3)return false;if(/_alternating_digits$/.test(b.family)&&f.L<4)return false}
 const dl=String(n).length;
 // A "constant mirrored-pair" property needs at least two independent mirrored pairs; otherwise it is vacuous.
 if((b.family==='dec_symmetric_pair_sum_constant'||b.family==='dec_symmetric_pair_product_constant')&&dl<4)return false;
 // We deliberately require four digits here: with three digits the condition collapses to first=last, i.e. just a palindrome.
 if(b.family==='dec_adjacent_pair_sum_constant'&&dl<4)return false;
 if((b.family==='dec_complement_palindrome'||b.family==='dec_half_complement')&&dl<4)return false;
 if(b.family==='dec_difference_palindrome'&&dl<4)return false;
 return true
}
const specializedPrimeFamilies=new Set(['balanced_prime','carol_prime','chen_prime','circular_prime','cousin_prime_member','cuban_prime','eisenstein_split_prime','factorial_prime','fermat_prime_value','full_reptend_prime','gaussian_split_prime','kynea_prime','left_truncatable_prime','mersenne_prime_value','palindromic_prime','pierpont_prime','primorial_neighbor_prime','proth_prime','right_truncatable_prime','safe_prime','sexy_prime_member','sophie_germain_prime','twin_prime_member']);
const specializedCompositeFamilies=new Set(['achilles','carmichael','giuga','fibonacci_pseudoprime','perrin_pseudoprime','semiprime_shape','product_of_twin_primes','product_of_cousin_primes','product_of_sexy_primes','strong_pseudoprime_base_2','strong_pseudoprime_base_3','strong_pseudoprime_base_5','strong_pseudoprime_base_7','strong_pseudoprime_base_11','fermat_pseudoprime_base_2','fermat_pseudoprime_base_3','fermat_pseudoprime_base_5','fermat_pseudoprime_base_7','fermat_pseudoprime_base_11','fermat_pseudoprime_base_13']);
function binomialCertificate(f,n){
 const canon=(N,K)=>`C:${N}:${Math.min(K,N-K)}`,choose=(N,K)=>{K=Math.min(K,N-K);let r=1;for(let i=1;i<=K;i++)r=r*(N-K+i)/i;return Math.round(r)};
 if(f==='triangular'){for(let k=0;k<2000;k++)if(k*(k+1)/2===n)return canon(k+1,2)}
 if(f==='tetrahedral_value'){for(let k=0;k<1000;k++)if(k*(k+1)*(k+2)/6===n)return canon(k+2,3)}
 if(f==='four_simplex_value'){for(let k=0;k<300;k++)if(((k)*(k+1)*(k+2)*(k+3))/24===n)return canon(k+3,4)}
 if(f==='central_binomial_value'){for(let k=0;k<30;k++)if(choose(k*2,k)===n)return canon(k*2,k)}
 return''
}
function applyDominance(badges,n){
 const rem=new Set(),byF=new Map();for(const b of badges){if(!byF.has(b.family))byF.set(b.family,[]);byF.get(b.family).push(b)}const has=(f,v=null)=>v===null?byF.has(f):(byF.get(f)||[]).some(b=>b.variant===String(v)),drop=(f,v=null)=>{for(const b of byF.get(f)||[])if(v===null||b.variant===String(v))rem.add(b)},dropMany=(...fs)=>fs.forEach(f=>drop(f)),hasOEIS=a=>badges.some(b=>b.oeis===a),dropOEIS=a=>{for(const b of badges)if(b.oeis===a)rem.add(b)};
 // Generic primality is bookkeeping; a named prime/composite structure is the informative evidence.
 if(badges.some(b=>specializedPrimeFamilies.has(b.family)))drop('primality','prime');if(badges.some(b=>specializedCompositeFamilies.has(b.family)))drop('primality','composite');
 // Strong probable-prime tests strictly imply the corresponding Fermat test.
 for(const a of [2,3,5,7,11])if(has(`strong_pseudoprime_base_${a}`))drop(`fermat_pseudoprime_base_${a}`);
 // Nested smoothness classes: score only the strongest (smallest prime bound).
 if(has('5_smooth'))dropMany('11_smooth','17_smooth','31_smooth');else if(has('11_smooth'))dropMany('17_smooth','31_smooth');else if(has('17_smooth'))drop('31_smooth');
 // Perfect-power hierarchy and consequences.
 if(has('square_triangular')){dropMany('perfect_square','triangular','divisor_parity','powerful')}
 if(has('abundance','perfect'))drop('harmonic_divisor_number');
 if(has('perfect_sixth'))dropMany('perfect_cube','perfect_square','perfect_power','divisor_parity','powerful');
 else if(has('perfect_fourth'))dropMany('perfect_square','perfect_power','divisor_parity','powerful');
 else if(has('perfect_cube'))dropMany('perfect_power','powerful');
 else if(has('perfect_fifth'))dropMany('perfect_power','powerful');
 if(has('perfect_square'))dropMany('divisor_parity','powerful');
 // tau(n) is odd iff n is a square; an exact odd divisor count is therefore the stronger certificate.
 {const oddTau=(byF.get('divisor_count')||[]).some(b=>{const q=Number(b.variant);return Number.isInteger(q)&&q>0&&(q&1)});if(oddTau)dropMany('perfect_square','divisor_parity','powerful')}
 if(has('perfect_power'))drop('powerful');
 if(has('semiprime_shape','prime_square')){dropMany('perfect_square','perfect_power','divisor_parity','powerful');drop('bigomega','2');drop('omega_distinct','1');drop('divisor_count','3')}
 if(has('achilles'))drop('powerful');
 for(const f of ['product_of_twin_primes','product_of_cousin_primes','product_of_sexy_primes'])if(has(f)){drop('bigomega','2');drop('omega_distinct','2');drop('divisor_count','4')}
 // Named constructions dominate their generic supersets.
 if(has('taxicab_multiple'))drop('sum_two_cubes');if(has('both_hexagonal_halves'))drop('both_triangular_halves');if(has('cousin_prime_halves'))drop('prime_halves_diff_square');if(has('two_digit_chunks_multiplication'))drop('dec_contiguous_mul_equation');if(has('complement_halves_999'))drop('dec_half_complement');if(has('projective_plane_points')||has('projective_3space_points')||has('projective_4space_points'))drop('grassmannian_points');if(has('sum_of_consecutive_squares'))drop('centered_square');
 if(has('hexagonal'))drop('triangular');
 if(has('cuban_prime'))drop('centered_hexagonal_value');
 if(has('product_of_twin_primes'))drop('lie_algebra_dimension');
 if(has('mersenne_number')||has('mersenne_prime_value'))drop('stirling2_value');
 if(has('factorial_prime'))drop('near_factorial');
 if(has('primorial_neighbor_prime')||has('euclid_number'))drop('near_primorial');
 if(has('triangular')||has('tetrahedral_value')||has('four_simplex_value')||has('central_binomial_value'))drop('pascal_value');
 // Mersenne/base-2 repdigits make the 1-bit-position AP automatic.
 if(has('mersenne_number')||has('mersenne_prime_value')||has('base2_repdigit')||badges.some(b=>b.oeis==='A000225'))drop('binary_one_positions_ap');
 // Decimal symmetry hierarchy: keep the strongest source of the same mirror evidence.
 const genericReverse=()=>dropMany('n_times_reverse_square','dec_reverse_product_square');
 if(has('base10_repdigit')){drop('multi_base_palindrome');dropMany('base10_palindrome','mirror_halves','repeat_halves','dec_half_reverse','dec_anagram_halves','dec_balanced_halves_sum','dec_balanced_torque','dec_difference_palindrome','dec_adjacent_pair_sum_constant','dec_symmetric_pair_sum_constant','dec_symmetric_pair_product_constant');for(const b of byF.get('dec_repeating_block')||[])rem.add(b);genericReverse()}
 else if(has('reverse_prime_halves')){drop('multi_base_palindrome');dropMany('mirror_halves','dec_half_reverse','base10_palindrome','dec_anagram_halves','dec_balanced_halves_sum','dec_balanced_torque','dec_difference_palindrome');genericReverse()}
 else if(has('mirror_halves')){drop('multi_base_palindrome');dropMany('dec_half_reverse','base10_palindrome','dec_anagram_halves','dec_balanced_halves_sum','dec_balanced_torque','dec_difference_palindrome');genericReverse()}
 else if(has('dec_half_reverse')){drop('multi_base_palindrome');dropMany('base10_palindrome','dec_anagram_halves','dec_balanced_halves_sum','dec_balanced_torque','dec_difference_palindrome');genericReverse()}
 else if(has('base10_palindrome')){dropMany('dec_balanced_torque','dec_difference_palindrome');genericReverse()}
 // Some short repdigits are encoded only as a period-1 repeated block; they are still decimal palindromes, so reversal-square evidence is automatic.
 if(has('dec_repeating_block','1')){dropMany('base10_palindrome','mirror_halves','repeat_halves','dec_half_reverse','dec_anagram_halves','dec_balanced_halves_sum','dec_balanced_torque','dec_difference_palindrome','dec_adjacent_pair_sum_constant','dec_symmetric_pair_sum_constant','dec_symmetric_pair_product_constant');genericReverse()}
 // A repdigit is a strictly stronger decimal digit-set description than 'all digits come from' a broad class.
 if(has('base10_repdigit')||has('dec_repeating_block','1'))dropMany('dec_prime_digits_only','dec_square_digits_only','dec_fibonacci_digits_only','dec_prefix_divisible_last_digit','dec_suffix_divisible_first_digit');
 // OEIS repunits/base-5 repdigits share a repetition evidence channel with their generic encodings; keep the higher-scoring representative.
 if(hasOEIS('A002275')){const pool=[...badges.filter(b=>b.oeis==='A002275'),...(byF.get('base10_repdigit')||[]),...(byF.get('dec_repeating_block')||[]).filter(b=>b.variant==='1')].filter(b=>!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}dropMany('dec_prime_digits_only','dec_square_digits_only','dec_fibonacci_digits_only','base10_zuckerman','circular_prime','dec_prefix_divisible_last_digit','dec_suffix_divisible_first_digit');genericReverse()}
 if(hasOEIS('A048330')){const pool=[...badges.filter(b=>b.oeis==='A048330'),...(byF.get('base5_repdigit')||[])].filter(b=>!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}}
 if(has('base10_repdigit')||has('dec_repeating_block','1'))drop('circular_prime');
 // 99...9 = 10^k-1: Kaprekar, trimorphic and n(n+2) palindromicity are automatic consequences of that same form.
 {const z=String(n),all9=/^9+$/.test(z);if(all9){const fundamental=has('base10_repdigit')||has('dec_repeating_block','1');if(fundamental)drop('base10_kaprekar');drop('base10_trimorphic');dropOEIS('A028503');dropOEIS('A069000');if(z.length%2===1)dropOEIS('A175823');if(!fundamental&&has('base10_kaprekar')){/* Kaprekar is the retained representative when the repdigit badge is absent. */}}}
 // Two independent 9-complement symmetries together force aa(9-a)(9-a)-type mirrored products, so that product badge is a consequence, not a third phenomenon.
 if(has('dec_half_complement')&&has('dec_complement_palindrome'))drop('dec_symmetric_pair_product_constant');
 // A repeated decimal block already explains an equal-frequency hit whenever the repeated word yields equal symbol counts.
 if(has('dec_repeating_block')&&baseFacts(n,10).equalFrequency){drop('dec_equal_frequency_used');drop('base_equal_frequency','10')}
 // Every 11...1 repunit has digit product 1, so its Zuckerman hit is vacuous once the repunit structure is known.
 if(/^1{2,}$/.test(String(n))&&(has('base10_repdigit')||has('dec_repeating_block','1')||hasOEIS('A002275')))drop('base10_zuckerman');
 if(has('palindromic_prime')){drop('base10_palindrome');drop('multi_base_palindrome')};if(has('dec_anagram_halves'))drop('dec_balanced_halves_sum');if(has('reverse_product_square_nonpal'))genericReverse();if(has('multi_base_arithmetic_digits'))drop('dec_arithmetic_progression');
 // When a cross-base event already includes base 10, its decimal-only statement is one constituent of the stronger persistence event.
 if(has('multi_base_sum_product')&&baseFacts(n,10).L>=3&&digitProduct(baseFacts(n,10).r)>0&&digitSum(baseFacts(n,10).r)===digitProduct(baseFacts(n,10).r))drop('dec_digit_sum_equals_product');
 if(has('multi_base_polydivisible')){const z=baseFacts(n,10),ok=z.L>=4&&z.a.every((_,i)=>Number(z.r.slice(0,i+1))%(i+1)===0);if(ok)drop('dec_prefix_polydivisible')}
 if(has('multi_base_alternating_sum')&&baseFacts(n,10).alternatingSum)drop('dec_alternating_sum_equal');
 if(has('multi_base_balanced_halves')&&baseFacts(n,10).balancedHalves)drop('dec_balanced_halves_sum');
 if(has('multi_base_antipalindrome')){const z=baseFacts(n,10);if(z.L>=4&&z.a.every((x,i)=>x+z.a[z.L-1-i]===9))drop('dec_complement_palindrome')}
 // If base 10 participates in the repeated digit-sum class, the exact decimal sum is not a second independent surprise.
 if(has('cross_base_same_digit_sum')){const need=Math.max(...(byF.get('cross_base_same_digit_sum')||[]).map(b=>Number(b.variant)||0)),z10=baseFacts(n,10),s10=digitSum(z10.r);if(z10.L>=3){let c=0;for(let bb=2;bb<=10;bb++){const z=baseFacts(n,bb);if(z.L>=3&&digitSum(z.r)===s10)c++}if(c>=need)drop('base10_digit_sum')}}
 if((has('base10_palindrome')||has('mirror_halves')||has('dec_half_reverse')||has('base10_repdigit')||has('palindromic_prime'))&&has('perfect_cube'))drop('n_times_reverse_cube');
 // Decimal halves: identical/reversed/anagram halves automatically give equal half sums/products.
 {const hs=String(n);if(hs.length%2===0){const h=hs.length/2,L=hs.slice(0,h),R=hs.slice(h),rev=L.split('').reverse().join(''),sort=x=>x.split('').sort().join(''),sum=x=>[...x].reduce((a,d)=>a+Number(d),0),prod=x=>[...x].reduce((a,d)=>a*Number(d),1);const explicitRepeat=has('repeat_halves')||(has('dec_repeating_block')&&L===R),explicitReverse=has('mirror_halves')||has('dec_half_reverse')||has('reverse_prime_halves'),strongAnagram=explicitRepeat||explicitReverse||has('dec_anagram_halves');if((explicitRepeat||explicitReverse)&&sort(L)===sort(R))drop('dec_anagram_halves');if(strongAnagram&&sort(L)===sort(R)){drop('dec_balanced_halves_sum');if(sum(L)===sum(R))drop('dec_split_same_digit_sum');if(prod(L)===prod(R))drop('dec_split_same_digit_product')}else if(has('dec_balanced_halves_sum')&&sum(L)===sum(R))drop('dec_split_same_digit_sum')}}
 // If a decimal split has equal nonzero digit products P on both sides, the total digit product is automatically P².
 if(has('dec_split_same_digit_product'))drop('dec_digit_product_square');
 // Exact binomial-certificate collisions: e.g. 6=C(4,2) is both triangular and central-binomial, 20=C(6,3) is tetrahedral and central-binomial, 70=C(8,4) is 4-simplex and central-binomial. Count that one coefficient only once.
 {const certs=[];for(const b of badges){if(rem.has(b))continue;const k=binomialCertificate(b.family,n);if(k)certs.push([k,b])}const bm=new Map();for(const [k,b] of certs){const old=bm.get(k);if(!old||b.ep>old.ep){if(old)rem.add(old);bm.set(k,b)}else rem.add(b)}}
  // For three decimal digits, equal adjacent-pair sums are exactly the palindrome condition a=b? no: a+b=b+a -> first=last. Keep only one evidence channel.
 {const L=String(n).length;if(L===3&&has('dec_adjacent_pair_sum_constant')){if(has('palindromic_prime')||has('multi_base_palindrome'))drop('dec_adjacent_pair_sum_constant');else if(has('base10_palindrome'))drop('base10_palindrome')}else if(L%2===1&&L>3&&has('dec_adjacent_pair_sum_constant')&&has('base10_palindrome'))drop('base10_palindrome')}
 // Short decimal periods force several pair invariants; score the repeated block itself, not its automatic consequences.
 const ds=String(n);for(let per=1;per<=2;per++){if(ds.length>=2*per&&ds.length%per===0&&ds===ds.slice(0,per).repeat(ds.length/per)){dropMany('dec_adjacent_pair_sum_constant','dec_symmetric_pair_sum_constant','dec_symmetric_pair_product_constant');break}}
 // A decimal arithmetic progression already contains its monotonic/distinct information. Step ±1 also gives the consecutive/cyclic badges.
 const dap=(byF.get('dec_arithmetic_progression')||[]).find(b=>!rem.has(b));if(dap){dropMany('dec_strict_increasing','dec_strict_decreasing','dec_symmetric_pair_sum_constant','dec_difference_palindrome');if(Math.abs(Number(dap.variant))===1)dropMany('dec_cyclic_consecutive','dec_consecutive_set','dec_zeroless_consecutive')}
 if(has('dec_zeroless_consecutive'))drop('dec_consecutive_set');
 if(has('dec_pandigital_interval')){dropMany('dec_consecutive_set','dec_zeroless_consecutive','dec_equal_frequency_used');for(const b of badges)if(baseFromBadge(b)===10&&(b.family==='base_all_distinct'||b.family==='base_equal_frequency'||b.family==='base10_all_digits_distinct'||b.family==='base10_all_digits_equal_frequency'))rem.add(b)}
 if(has('dec_symmetric_pair_sum_constant'))drop('dec_difference_palindrome');
 if(String(n).length===4&&has('dec_alternating_sum_equal'))drop('dec_difference_palindrome');
 if(has('complement_halves_999'))drop('dec_digit_sum_cube');
 // Binary/base-power representation implications.
 if(has('base2_alternating_digits'))dropMany('binary_equal_run_lengths','binary_one_positions_ap');if(has('base2_monotone_digits'))drop('binary_one_positions_ap');if(has('base2_palindrome'))drop('binary_palindromic_run_lengths');if(has('base4_repdigit'))dropMany('binary_equal_run_lengths','binary_one_positions_ap','base2_alternating_digits');if(has('base8_repdigit'))drop('binary_one_positions_ap');
 // A prime primorial neighbor that is also a Euclid number is the stronger named construction.
 if(has('primorial_neighbor_prime')&&has('euclid_number'))drop('euclid_number');
 // Constant mirrored sums and products together encode one unordered mirrored-pair signature; keep only the more informative one.
 if(has('dec_symmetric_pair_sum_constant')&&has('dec_symmetric_pair_product_constant')){const pool=[...(byF.get('dec_symmetric_pair_sum_constant')||[]),...(byF.get('dec_symmetric_pair_product_constant')||[])].filter(b=>!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}}
 // Same-base digit hierarchy: AP => strict monotone => all distinct; pandigital permutation => distinct/equal-frequency.
 for(let base=2;base<=10;base++){const same=b=>baseFromBadge(b)===base,baseRows=badges.filter(same);if(!baseRows.length)continue;const f=baseFacts(n,base),hasRep=baseRows.some(b=>b.family===`base${base}_repdigit`);if(hasRep){for(const b of baseRows)if(b.family===`base${base}_palindrome`||b.family==='base_palindrome'||b.family===`base${base}_monotone_digits`)rem.add(b)}if(f.arithmetic){for(const b of baseRows)if(b.family==='base_strict_monotone'||b.family==='base_all_distinct'||b.family===`base${base}_all_digits_distinct`||b.family===`base${base}_monotone_digits`)rem.add(b)}else if(f.strictMonotone){for(const b of baseRows)if(b.family==='base_all_distinct'||b.family===`base${base}_all_digits_distinct`||b.family===`base${base}_monotone_digits`)rem.add(b)}if(f.allDistinct){for(const b of baseRows)if(b.family==='base_equal_frequency'||/_all_digits_equal_frequency$/.test(b.family))rem.add(b)}if(f.pandigital){for(const b of baseRows)if(b.family==='base_all_distinct'||b.family==='base_equal_frequency'||b.family===`base${base}_all_digits_distinct`||/_all_digits_equal_frequency$/.test(b.family))rem.add(b)}
  // Prime/square/triangular classifications of the same digit sum are one evidence channel per base.
  const sumPool=baseRows.filter(b=>['base_sum_prime','base_sum_square','base_sum_triangular'].includes(b.family)&&!rem.has(b));if(base===10)sumPool.push(...(byF.get('base10_digit_sum')||[]).filter(b=>!rem.has(b)));if(sumPool.length>1){const best=sumPool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of sumPool)if(b!==best)rem.add(b)}
 }
 // Decimal named encodings and their generic base-10 encodings are one channel when both are present.
 {const compete=(arr)=>{const pool=arr.filter(b=>b&&!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}};compete([...(byF.get('dec_strict_increasing')||[]),...(byF.get('dec_strict_decreasing')||[]),...(byF.get('base_strict_monotone')||[]).filter(b=>b.variant==='10')]);compete([...(byF.get('dec_alternating_parity')||[]),...(byF.get('base_alt_parity')||[]).filter(b=>b.variant==='10')]);compete([...(byF.get('dec_equal_frequency_used')||[]),...(byF.get('base_equal_frequency')||[]).filter(b=>b.variant==='10')])}
 // Pandigital permutations make distinct/equal-frequency bookkeeping automatic in that base.
 if(has('base6_pandigital_once'))for(const b of badges)if(baseFromBadge(b)===6&&(b.family==='base_all_distinct'||b.family==='base_equal_frequency'||b.family==='base6_all_digits_distinct'||b.family==='base6_all_digits_equal_frequency'))rem.add(b);
 if(has('multi_base_pandigital'))for(let base=2;base<=10;base++)if(baseFacts(n,base).pandigital)for(const b of badges)if(baseFromBadge(b)===base&&(b.family==='base_all_distinct'||b.family==='base_equal_frequency'||/_all_digits_distinct$/.test(b.family)||/_all_digits_equal_frequency$/.test(b.family)))rem.add(b);
 // Prime evidence already determines tau=2, omega=Omega=1.
 if(has('primality','prime')||badges.some(b=>specializedPrimeFamilies.has(b.family))){drop('divisor_count','2');drop('omega_distinct','1');drop('bigomega','1')}
 // Decimal AP exact variant and generic base-10 AP are one channel: keep the higher score.
 {const pool=[...(byF.get('dec_arithmetic_progression')||[]),...(byF.get('base_arithmetic_digits')||[]).filter(b=>b.variant==='10')].filter(b=>!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}}
 // Complement symmetry is exactly mirrored-pair sum 9 when both representations are present.
 if(has('dec_complement_palindrome')&&has('dec_symmetric_pair_sum_constant','9')){const pool=[...(byF.get('dec_complement_palindrome')||[]),...(byF.get('dec_symmetric_pair_sum_constant')||[]).filter(b=>b.variant==='9')].filter(b=>!rem.has(b));if(pool.length>1){const best=pool.reduce((a,b)=>b.ep>a.ep?b:a);for(const b of pool)if(b!==best)rem.add(b)}}
 // Counts of square roots and fourth roots of unity are related but not equivalent; keep both when independently exceptional.
 return badges.filter(b=>!rem.has(b))
}
function broadDomain(g){const b=g.rep,f=b.family||'',c=String(b.cat||'').toLowerCase(),ds=(b.domains||[]).join(' ').toLowerCase();if(g.synthetic)return'constellation';if(b.src==='x')return'special structure';if(/base|digit|decimal|binary/.test(f)||/digit/.test(c+ds))return'digit structure';if(/prime|pseudoprime/.test(f)||/prime/.test(c+ds))return'prime structure';if(/graph|tree/.test(c+ds))return'graphs';if(/combin|partition|permutation|tiling/.test(c+ds)||/_value$/.test(f))return'combinatorics';if(/geometry|figurate|polygon|projective|grassmann|root_system|flag/.test(f+c+ds))return'geometry';if(/algebra|field|cyclotomic|quadratic|residue|legendre|carmichael|mobius|totient/.test(f+c+ds))return'algebra & modular';if(/analysis|complex/.test(c+ds))return'analysis';if(/divisor|factor|smooth|abundan|perfect|tau|omega/.test(f+c+ds))return'divisibility';return'number theory'}

function resonanceMultiplier(family,k){k=Math.max(0,Math.min(9,Number(k)||0));if(k<=1)return 1;const f=String(family||'');let step=.09,cap=1.65;if(/harshad/.test(f)){step=.18;cap=2.45}else if(/palindrome|repdigit/.test(f)){step=.12;cap=1.9}else if(/polydivisible/.test(f)){step=.10;cap=1.6}else if(/arithmetic_digits/.test(f)){step=.11;cap=1.75}return Math.min(cap,1+step*(k-1))}
function domainQuality(name){if(name==='digit structure')return .35;if(name==='special structure')return .65;if(name==='graphs')return .9;return 1}
function groupKey(b){if(aggregateBaseFamily[b.family])return`B:${aggregateBaseFamily[b.family]}`;if(aggregateFamilies.has(b.family))return`M:${b.family}`;if(baseFam.has(b.family))return`B:${b.family}`;const m=b.family.match(/^base\d+_(palindrome|repdigit|all_digits_distinct|all_digits_equal_frequency|happy|monotone_digits|alternating_digits)$/);if(m){const norm=m[1]==='all_digits_distinct'?'all_distinct':m[1]==='all_digits_equal_frequency'?'equal_frequency':m[1];return`B:base_${norm}`}return`I:${b.id}`}
function groupBadges(ids,degree,n){
 let badges=ids.map(id=>badgeInfo(id,degree,n)).filter(b=>b&&b.ep>0&&badgeValid(b,n));
 // Exact semantic de-duplication: equivalent encodings compete for one scoring slot.
 const winner=new Map();for(const b of badges){const k=semanticKey(b);if(!k)continue;const old=winner.get(k);if(!old||b.ep>old.ep)winner.set(k,b)}
 badges=badges.filter(b=>{const k=semanticKey(b);return !k||winner.get(k)===b});
 // Strict implication / evidence-channel dominance: one mathematical reason should score once.
 badges=applyDominance(badges,n);
 const map=new Map();for(const b of badges){const k=groupKey(b);if(!map.has(k))map.set(k,[]);map.get(k).push(b)}
 const groups=[];
 for(const [key,items] of map){
  if(key.startsWith('B:')){
   const byBase=new Map(),loose=[];for(const b of items){const base=baseFromBadge(b);if(base){if(!byBase.has(base)||b.ep>byBase.get(base).ep)byBase.set(base,b)}else loose.push(b)}
   const bestLoose=loose.length?loose.reduce((a,b)=>b.ep>a.ep?b:a):null,baseItems=[...byBase.values()],keep=[...baseItems,...(bestLoose?[bestLoose]:[])];if(!keep.length)continue;const rep=keep.reduce((a,b)=>b.ep>a.ep?b:a),rare=keep.reduce((a,b)=>b.p<a.p?b:a);
   const k=byBase.size,mult=resonanceMultiplier(key.slice(2),k),baseEP=baseItems.length?Math.max(...baseItems.map(x=>x.ep)):0,aggregateEP=bestLoose?bestLoose.ep:0;
   const ep=Math.round(Math.max(aggregateEP,baseEP)*mult);const fam=key.slice(2);
   groups.push({key,items:keep,rep,ep,p:rare.p,rarity:rare.rarity,name:groupNames[fam]||rep.name,emoji:rep.emoji,baseGroup:true,baseCount:k,resonanceMultiplier:mult});
  }else if(key.startsWith('M:')){const best=items.reduce((a,b)=>b.ep>a.ep?b:a),k=aggregateBaseCount(best.family,n);if(k<=0)continue;const mult=resonanceMultiplier(best.family,k),ep=Math.round(best.ep*mult);groups.push({key,items:[best],rep:best,ep,p:best.p,rarity:best.rarity,name:best.name,emoji:best.emoji,baseGroup:false,aggregateGroup:true,baseCount:k,resonanceMultiplier:mult})
  }else{const b=items[0];groups.push({key,items:[b],rep:b,ep:b.ep,p:b.p,rarity:b.rarity,name:b.name,emoji:b.emoji,baseGroup:false})}
 }
 const realTotal=groups.reduce((a,g)=>a+g.ep,0),domains=[...new Set(groups.map(broadDomain))].filter(x=>x!=='number theory');
 const domainStrength=domains.reduce((a,d)=>a+domainQuality(d),0),constellationBase=groups.reduce((a,g)=>a+g.ep*domainQuality(broadDomain(g)),0);
 if(domains.length>=4&&domainStrength>=3.5&&groups.length>=4){const frac=Math.min(.52,Math.max(.10,(domainStrength-3)*.12)),ep=Math.round(constellationBase*frac),rarity=domainStrength>=6.5?'Mythic':domainStrength>=5.5?'Anomaly':domainStrength>=4.5?'Epic':'Rare';if(ep>0)groups.push({key:'CONSTELLATION',items:[],rep:{src:'z',name:`Constellation · ${domains.length} domains`,emoji:'✦ ∑ ✦',oeis:'',family:'constellation',cat:'constellation',domains,explain:'Independent mathematical structures converge on the same integer; representation-only domains count less than invariant mathematics.',ep},ep,p:0,rarity,name:`Constellation · ${domains.length} domains`,emoji:'✦ ∑ ✦',baseGroup:false,synthetic:true,domainNames:domains,bonusFraction:frac})}
 // Zero is a canonical mathematical object rather than a representation trick: reward its simultaneous
 // roles as additive identity, absorbing element and empty cardinality with one explicit, non-stacking bonus.
 if(n===0){const real=groups.reduce((a,g)=>a+g.ep,0),ep=65000000;groups.push({key:'FOUNDATIONAL_ZERO',items:[],rep:{src:'z',name:'Foundational constant · 0',emoji:'0 ∅ +',oeis:'',family:'foundational_zero',cat:'foundational',domains:['algebra','set theory'],explain:'0 is simultaneously the additive identity, the absorbing element for multiplication, and the cardinality of the empty set.',ep},ep,p:1/U,rarity:'Mythic',name:'Foundational constant · 0',emoji:'0 ∅ +',baseGroup:false,synthetic:true,domainNames:['additive identity','multiplicative zero','empty cardinality'],bonusFraction:0,foundational:true})}
 return groups;
}
function totalScore(groups){return groups.reduce((s,g)=>s+g.ep,0)}

function numberRarity(score){const q=CFG.scoreQuantiles;if(score>=q['0.99'])return['Mythic','Top 1%'];if(score>=q['0.95'])return['Anomaly','Top 5–1%'];if(score>=q['0.9'])return['Epic','Top 10–5%'];if(score>=q['0.75'])return['Rare','Top 25–10%'];if(score>=q['0.5'])return['Uncommon','Top 50–25%'];if(score<=q['0.01'])return['Trash','Bottom 1%'];return['Common','Bottom 50%']}
function exactPercentile(score){const rank=exactTopRank(score);if(rank&&rank<=100)return'Top 0.01%';if(rank&&rank<=1000)return'Top 0.1%';const p=CFG.scorePercentiles;let lo=0,hi=100;while(lo<hi){const mid=(lo+hi)>>1;if(p[mid]<score)lo=mid+1;else hi=mid}const bottom=Math.max(0,lo),top=Math.max(1,100-bottom);return bottom>=50?`Top ${top}%`:`Bottom ${bottom||1}%`}
function exactTopRank(score){const a=CFG.topRankScores||[];for(let i=0;i<a.length;i++)if(score>=a[i])return i+1;return null}
function jackpotInfo(score){const rank=exactTopRank(score);if(rank&&rank<=100)return{tier:'ULTRA JACKPOT',detail:'Top 0.01%',ultra:true,rank};if(rank&&rank<=1000)return{tier:'JACKPOT',detail:'Top 0.1%',ultra:false,rank};return null}

function factorize(n){if(n<2)return[];let x=n,out=[];for(let p=2;p*p<=x;p+=(p===2?1:2)){if(x%p===0){let e=0;while(x%p===0){x/=p;e++}out.push([p,e])}}if(x>1)out.push([x,1]);return out}
function factorText(n){if(n===0)return'0 has no prime factorization';if(n===1)return'1 is the empty product';return`${n} = `+factorize(n).map(([p,e])=>e===1?`${p}`:`${p}^${e}`).join(' × ')}
function tau(n){if(n<1)return 0;return factorize(n).reduce((a,[,e])=>a*(e+1),1)}
function omega(n){return factorize(n).length}function bigomega(n){return factorize(n).reduce((a,[,e])=>a+e,0)}
function phi(n){if(n===0)return 0;let v=n;for(const[p]of factorize(n))v=v/p*(p-1);return Math.round(v)}
function isPrime(n){if(n<2)return false;if(n%2===0)return n===2;for(let p=3;p*p<=n;p+=2)if(n%p===0)return false;return true}
function mobius(n){if(n===1)return 1;const f=factorize(n);if(f.some(([,e])=>e>1))return 0;return f.length%2?-1:1}
function toBase(n,b){return Math.max(0,n).toString(b).toUpperCase()}
function digitsOf(rep){return[...rep].map(c=>parseInt(c,36))}function digitSum(rep){return digitsOf(rep).reduce((a,b)=>a+b,0)}function digitProduct(rep){return digitsOf(rep).reduce((a,b)=>a*b,1)}
function reverse10(n){return Number(String(n).split('').reverse().join(''))}
function isSquare(n){const r=Math.floor(Math.sqrt(n));return r*r===n}
function findEquation(n,op){const s=String(n);for(let i=1;i<s.length-1;i++)for(let j=i+1;j<s.length;j++){const a=Number(s.slice(0,i)),b=Number(s.slice(i,j)),c=Number(s.slice(j));if(op==='+'&&a>0&&b>0&&c>9&&a+b===c)return`${a} + ${b} = ${c}`;if(op==='-'&&a>9&&b>0&&c>0&&a-b===c)return`${a} − ${b} = ${c}`;if(op==='*'&&a>1&&b>1&&c>9&&a*b===c)return`${a} × ${b} = ${c}`;if(op==='/'&&b>1&&c>1&&a===b*c)return`${a} ÷ ${b} = ${c}`}return''}
function specialProof(f,n){const bm=f.match(/^base(\d+)_(.*)$/);if(bm){const b=Number(bm[1]),rep=toBase(n,b),a=digitsOf(rep),sum=digitSum(rep);return`${n} = ${rep} in base ${b}; digit sum = ${a.join(' + ')} = ${sum}.`}if(f==='two_digit_chunks_pythagorean'){const s=String(n).padStart(6,'0'),a=+s.slice(0,2),b=+s.slice(2,4),c=+s.slice(4);return`${a}² + ${b}² = ${c}².`}if(f==='two_digit_chunks_multiplication'){const s=String(n).padStart(6,'0'),a=+s.slice(0,2),b=+s.slice(2,4),c=+s.slice(4);return`${a} × ${b} = ${c}.`}if(f==='three_two_digit_squares'){const s=String(n),a=[+s.slice(0,2),+s.slice(2,4),+s.slice(4)];return`${a.join(', ')} are all perfect squares.`}if(f==='n_plus_reverse_square'){const r=reverse10(n),q=Math.round(Math.sqrt(n+r));return`${n} + ${r} = ${n+r} = ${q}².`}if(f==='sum_of_consecutive_squares'){for(let k=1;k*k+(k+1)*(k+1)<=n;k++)if(k*k+(k+1)*(k+1)===n)return`${n} = ${k}² + ${k+1}².`}if(f.startsWith('product_of_')){const z=factorize(n);if(z.length===2&&z.every(x=>x[1]===1))return`${n} = ${z[0][0]} × ${z[1][0]}; prime gap = ${Math.abs(z[1][0]-z[0][0])}.`}if(f==='palindrome_in_two_bases'){const a=[];for(let b=2;b<=10;b++){const r=toBase(n,b);if(r.length>2&&r===r.split('').reverse().join(''))a.push(`base ${b}: ${r}`)}return a.join(' · ')}if(f==='alternating_parity_in_three_bases'){const a=[];for(let b=2;b<=10;b++){const r=digitsOf(toBase(n,b));if(r.length>=5&&r.slice(1).every((x,i)=>((x^r[i])&1)===1))a.push(`base ${b}`)}return`Alternation occurs in ${a.join(', ')}.`}return''}
function proofFor(b,n){if(b.src==='x')return specialProof(b.family,n);const fam=b.family,base=baseFromBadge(b);if(base){const rep=toBase(n,base),ds=digitsOf(rep);if(fam.includes('palindrome'))return`${n} = ${rep} in base ${base}, and reversing the digits gives ${rep}.`;if(fam.includes('equal_frequency')){const c={};ds.forEach(x=>c[x]=(c[x]||0)+1);return`${rep} (base ${base}); counts: ${Object.entries(c).map(([k,v])=>`${k}:${v}`).join(', ')}.`}if(fam.includes('sum_prime')||fam.includes('sum_square')||fam.includes('sum_triangular'))return`${rep} (base ${base}); digit sum = ${ds.join(' + ')} = ${digitSum(rep)}.`;if(fam.includes('product_square'))return`${rep} (base ${base}); digit product = ${ds.join(' × ')} = ${digitProduct(rep)}.`;if(fam.includes('all_distinct'))return`${rep} (base ${base}); all ${ds.length} digit positions use distinct symbols.`;return`${n} = ${rep} in base ${base}.`}if(fam==='primality')return isPrime(n)?`${n} has no divisor from 2 through √${n}.`:`${factorText(n)}.`;if(fam==='divisor_count')return`${factorText(n)}; τ(${n}) = ${tau(n)}.`;if(fam==='omega_distinct')return`${factorText(n)}; ω(${n}) = ${omega(n)}.`;if(fam==='bigomega')return`${factorText(n)}; Ω(${n}) = ${bigomega(n)}.`;if(fam==='mobius')return`${factorText(n)}; μ(${n}) = ${mobius(n)}.`;if(fam.includes('totient')||b.name.toLowerCase().includes('totient'))return`φ(${n}) = ${phi(n)}.`;if(fam.includes('contiguous_add'))return findEquation(n,'+');if(fam.includes('contiguous_sub'))return findEquation(n,'-');if(fam.includes('contiguous_mul'))return findEquation(n,'*');if(fam.includes('contiguous_div'))return findEquation(n,'/');return''}

function witnessHue(b){const f=String(b?.family||''),c=String(b?.cat||'').toLowerCase();if(b?.src==='x'){if(/prime_halves|prime_chunks|reverse_prime/.test(f))return 282;if(/square|cube|triangular|pentagonal|hexagonal|heptagonal|octagonal/.test(f))return 326;if(/chunks/.test(f))return 198;if(/reverse/.test(f))return 158;if(/fibonacci|lucas/.test(f))return 42;if(/halves/.test(f))return 18;let h=0;for(const ch of f)h=(Math.imul(h,31)+ch.charCodeAt(0))>>>0;return h%360}if(/digit|base|decimal|binary/.test(f+c))return 207;if(/prime|pseudoprime|reptend/.test(f+c))return 278;if(/geometry|figurate|polygon|grassmann|projective/.test(f+c))return 326;if(/combin|partition|sequence|_value|leyland/.test(f+c))return 36;if(/algebra|field|residue|cyclotomic|modular|totient|mobius/.test(f+c))return 175;if(/graph|tree/.test(f+c))return 145;return 225}
function isDecimalHalfFamily(b){const f=String(b?.family||'');if(f==='multi_base_balanced_halves')return false;if(b?.src==='x'&&(/halves/.test(f)||/half_gap/.test(f)))return true;return /^dec_(anagram_halves|balanced_halves_sum|half_complement|half_reverse)$/.test(f)}
function witnessRoleMap(b,n,text){const roles=new Map(),target=String(n);roles.set(target,'target');const raw=String(n),f=String(b?.family||'');if(isDecimalHalfFamily(b)&&raw.length%2===0){const h=raw.length/2,A=raw.slice(0,h),B=raw.slice(h);roles.set(A,'a');roles.set(String(Number(A)),'a');roles.set(B,'b');roles.set(String(Number(B)),'b')}if(/chunks|two_digit|three_two_digit/.test(f)&&raw.length===6){for(const [i,q]of [raw.slice(0,2),raw.slice(2,4),raw.slice(4)].entries()){roles.set(q,['a','b','c'][i]);roles.set(String(Number(q)),['a','b','c'][i])}}const palette=['a','b','c','d'];let j=0;for(const m of String(text).matchAll(/\b\d+(?:\.\d+)?\b/g)){const z=m[0];if(!roles.has(z))roles.set(z,palette[j++%palette.length])}return roles}
function mathHTML(text,roles){const re=/(\b\d+(?:\.\d+)?\b|(?:F|P|C|S|B|ord|mod|gcd|lcm|phi|sigma|tau|mu|omega)(?:_?\d+)?|[φτσμωΩ]|[=+×÷−±<>≤≥≡→|·²³^/]+)/g;let out='',last=0,m;while((m=re.exec(String(text)))){out+=esc(text.slice(last,m.index));const t=m[0];let cl='math-op';if(/^\d/.test(t))cl='math-'+(roles?.get(t)||'value');else if(/^(?:F|P|C|S|B|ord|mod|gcd|lcm|phi|sigma|tau|mu|omega|[φτσμωΩ])/.test(t))cl='math-fn';out+=`<span class="${cl}">${esc(t)}</span>`;last=m.index+t.length}return out+esc(String(text).slice(last))}
function splitPreviewHTML(b,n){const f=String(b?.family||''),raw=String(n);if(isDecimalHalfFamily(b)&&raw.length>=2&&raw.length%2===0){const h=raw.length/2;return`<div class="number-split"><span class="split-part role-a">${esc(raw.slice(0,h))}</span><span class="split-bar">|</span><span class="split-part role-b">${esc(raw.slice(h))}</span></div>`}if(/chunks|two_digit|three_two_digit/.test(f)&&raw.length===6)return`<div class="number-split chunks"><span class="split-part role-a">${esc(raw.slice(0,2))}</span><span class="split-bar">|</span><span class="split-part role-b">${esc(raw.slice(2,4))}</span><span class="split-bar">|</span><span class="split-part role-c">${esc(raw.slice(4))}</span></div>`;return''}
function multiBaseHalvesHTML(n){const rows=[];for(let b=2;b<=10;b++){const rep=toBase(n,b),ds=digitsOf(rep),L=ds.length,h=L/2;if(L<4||L%2)continue;const a=ds.slice(0,h),c=ds.slice(h),sa=a.reduce((x,y)=>x+y,0),sb=c.reduce((x,y)=>x+y,0);if(sa!==sb)continue;rows.push(`<div class="mb-half-row"><span class="base-chip">BASE ${b}</span><div><div class="number-split base-split"><span class="split-part role-a">${esc(rep.slice(0,h))}</span><span class="split-bar">|</span><span class="split-part role-b">${esc(rep.slice(h))}</span></div><div class="half-sum"><span class="role-a">${esc(a.join(' + '))}</span><span class="math-op"> = </span><span class="math-target">${sa}</span><span class="half-eq">and</span><span class="role-b">${esc(c.join(' + '))}</span><span class="math-op"> = </span><span class="math-target">${sb}</span></div></div></div>`)}return rows.length?`<div class="mb-halves">${rows.join('')}</div>`:''}
function proofVisualHTML(b,n,text){
 if(!text)return'';
 if(String(b?.family||'')==='multi_base_balanced_halves')return multiBaseHalvesHTML(n);
 const preview=splitPreviewHTML(b,n),f=String(b?.family||''),raw=String(n),parts=String(text).split(/\s*[;]\s*|\s+·\s+/).filter(Boolean),roles=witnessRoleMap(b,n,text);
 let lines=parts;
 if(preview&&lines.length){
  if(isDecimalHalfFamily(b)&&raw.length%2===0){const h=raw.length/2,re=new RegExp(`^${raw.slice(0,h)}\\s*\\|\\s*0*${Number(raw.slice(h))}\\.?$`);if(re.test(lines[0]))lines=lines.slice(1)}
  else if(/chunks|two_digit|three_two_digit/.test(f)&&raw.length===6&&new RegExp(`^${raw.slice(0,2)}\\s*\\|`).test(lines[0]))lines=lines.slice(1)
 }
 return preview+`<div class="witness-lines">${lines.map(x=>`<span class="math-line">${mathHTML(x,roles)}</span>`).join('')}</div>`;
}
function enrichmentHTML(b,n){const d=b.detail;if(!d)return'';const fs=d.f||[],cs=d.c||[],es=d.e||[],ks=d.k||[],terms=d.t||[];if(!fs.length&&!cs.length&&!es.length&&!ks.length&&!terms.length&&!b.oeis)return'';let h='<div class="oeis-enrichment">';if(terms.length){let exact=terms.findIndex(x=>x===n),idx=exact;if(idx<0){idx=terms.findIndex(x=>x>n);if(idx<0)idx=terms.length-1}const windowSize=11,half=5,a=Math.max(0,Math.min(Math.max(0,terms.length-windowSize),idx-half)),near=terms.slice(a,a+windowSize),pos=exact>=0?` · local member ${fmt(exact+1)} of ${fmt(terms.length)}`:` · ${fmt(terms.length)} local members`;h+=`<div class="oeis-sequence"><b>Sequence neighborhood</b><div class="oeis-terms">${near.map(x=>`<span class="oeis-term${x===n?' current':''}">${fmt(x)}</span>`).join('<span class="oeis-term-sep">·</span>')}</div><small>Members within 0–999,999${pos}. The highlighted value is the current number.</small></div>`}for(const x of fs)h+=`<div class="oeis-note formula"><b>Formula</b><span>${esc(x)}</span></div>`;for(const x of cs)h+=`<div class="oeis-note comment"><b>Comment</b><span>${esc(x)}</span></div>`;for(const x of es)h+=`<div class="oeis-note example"><b>Example</b><span>${esc(x)}</span></div>`;if(ks.length)h+=`<div class="oeis-keywords"><b>OEIS keywords</b>${ks.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;if(b.oeis)h+=`<a class="oeis-link" href="https://oeis.org/${encodeURIComponent(b.oeis)}" target="_blank" rel="noopener noreferrer">Open ${esc(b.oeis)} on OEIS ↗</a>`;return h+'</div>'}
function renderGroup(g,n,animated){const rep=g.rep;let title=g.name,oeis=rep.oeis?`OEIS ${rep.oeis}`:'';if(rep.oeis&&!g.baseGroup)title=rep.name;const witness=window.MR_WITNESS;let explain=g.synthetic?rep.explain:(rep.oeis?(rep.explain||''):(witness?.definitionFor(rep,n)||rep.explain||''));let proof='';
 if(g.synthetic){proof=g.foundational?`<div class="constellation-domains">${g.domainNames.map(x=>`<span class="domain-chip">${esc(x)}</span>`).join('')}</div><div class="resonance-note">Canonical-constant bonus · counted once</div>`:`<div class="constellation-domains">${g.domainNames.map(x=>`<span class="domain-chip">${esc(x)}</span>`).join('')}</div><div class="resonance-note">Cross-domain bonus · +${Math.round(g.bonusFraction*100)}% of beauty-weighted EP</div>`}
 else if(g.baseGroup){const lines=[];for(const b of [...g.items].sort((a,b)=>(baseFromBadge(a)||99)-(baseFromBadge(b)||99))){const base=baseFromBadge(b),w=witness?.proofFor(b,n)||proofFor(b,n);if(base)lines.push(`<div class="base-hit"><span class="base-chip">BASE ${base}</span><div class="base-proof">${proofVisualHTML(b,n,w)}</div><small>${chanceText(b.p)}</small></div>`);else if(w)lines.push(`<div class="base-hit aggregate"><span class="base-chip">FAMILY</span><div class="base-proof">${proofVisualHTML(b,n,w)}</div></div>`)}const res=g.baseCount>=2?`<div class="resonance-note"><b>${g.baseCount} bases persist</b> · resonance ×${Number(g.resonanceMultiplier).toFixed(g.resonanceMultiplier%1?2:1)}</div>`:'';proof=res+lines.join('')}
 else{const w=rep.oeis?'':(witness?.proofFor(rep,n)||proofFor(rep,n));const res=g.aggregateGroup&&g.baseCount>=2?`<div class="resonance-note"><b>${g.baseCount} bases persist</b> · resonance ×${Number(g.resonanceMultiplier).toFixed(g.resonanceMultiplier%1?2:1)}</div>`:'';proof=res+proofVisualHTML(rep,n,w)}
 const card=document.createElement('article');card.className=`badge-card ${g.rarity}${animated?' animated':''}${g.synthetic?' constellation-card':''}`;const wh=witnessHue(rep);card.style.setProperty('--witness-h',String(wh));card.style.setProperty('--math-a-h',String((wh+18)%360));card.style.setProperty('--math-b-h',String((wh+104)%360));card.style.setProperty('--math-c-h',String((wh+184)%360));card.style.setProperty('--math-d-h',String((wh+258)%360));const chance=g.foundational?'unique canonical constant':g.synthetic?`${g.domainNames.length} independent domains`:chanceText(g.p);card.innerHTML=`<div class="badge-row"><div class="badge-emoji">${esc(g.emoji)}</div><div class="badge-main"><div class="badge-meta">${oeis?`<span class="oeis-label">${esc(oeis)}</span>`:''}<span class="badge-rarity ${g.rarity}">${esc(g.rarity)}</span></div><h3 class="badge-title">${esc(title)}</h3><p class="badge-explain">${esc(explain)}</p></div><div class="badge-side"><div class="badge-ep">+${fmt(g.ep)} <small>EP</small></div><div class="badge-chance">${esc(chance)}</div></div></div>${proof?`<div class="badge-proof"><span class="witness-label">For ${n}</span>${proof}</div>`:''}${rep.oeis?enrichmentHTML(rep,n):''}`;return card}

function animateScore(el,from,to,dur=320){return new Promise(resolve=>{if(matchMedia('(prefers-reduced-motion:reduce)').matches){el.textContent=fmt(to);resolve();return}const st=performance.now();function f(t){let q=Math.min(1,(t-st)/dur);q=1-Math.pow(1-q,3);el.textContent=fmt(from+(to-from)*q);if(q<1)requestAnimationFrame(f);else resolve()}requestAnimationFrame(f)})}
function instantNumber(n){$('#numberStage')?.classList.remove('rolling');$('#rollOrbit')?.classList.add('hidden');$('#number').textContent=String(n)}
async function slowNumber(n){const el=$('#number'),stage=$('#numberStage'),orbit=$('#rollOrbit');el.innerHTML='';stage.classList.add('rolling');orbit?.classList.remove('hidden');await sleep(850);orbit?.classList.add('hidden');for(const ch of String(n)){const s=document.createElement('span');s.className='digit';s.textContent=ch;el.appendChild(s);await sleep(440)}await sleep(250);stage.classList.remove('rolling')}
function setBusy(v){busy=v;for(const id of ['randomButton','numberInput']){const el=$('#'+id);if(el)el.disabled=v}}
function clearResult(){currentResult=null;$('#results')?.classList.add('hidden');if($('#badgeStack'))$('#badgeStack').innerHTML='';const line=$('#resultLine');line?.classList.add('hidden');line?.classList.remove('scoring');$('#numberRarity')?.classList.add('hidden');$('#rankText')?.classList.add('hidden');$('#shareButton')?.classList.add('hidden');$('#rollActions')?.classList.add('single');if($('#score'))$('#score').textContent='0';$('#jackpotBanner')?.classList.add('hidden')}
function setHeader(score){const[rar,label]=numberRarity(score),rp=$('#numberRarity'),rk=$('#rankText'),line=$('#resultLine');rp.textContent=rar.toUpperCase();rp.className=`rarity-pill ${rar}`;rk.textContent=exactPercentile(score);rp.classList.remove('hidden');rk.classList.remove('hidden');line.classList.remove('hidden','scoring');const j=jackpotInfo(score),banner=$('#jackpotBanner');if(banner){if(j){const rank=exactTopRank(score);$('#jackpotTier').textContent=j.tier;$('#jackpotRank').textContent=rank?`#${fmt(rank)} / ${fmt(U)}`:'';$('#jackpotDetail').textContent=j.detail;banner.className=`jackpot-banner${j.ultra?' ultra':''}`}else banner.classList.add('hidden')}return rar}

async function revealResult(n,row,animate){await loadDetailsForIds(row.ids);let groups=groupBadges(row.ids,row.degree,n);const score=totalScore(groups),rarity=numberRarity(score)[0];$('#results').classList.remove('hidden');$('#badgeTotal').textContent=`${groups.length} scoring badges`;const stack=$('#badgeStack');stack.innerHTML='';let total=0;$('#score').textContent='0';if(animate){const line=$('#resultLine');line.classList.remove('hidden');line.classList.add('scoring');$('#numberRarity')?.classList.add('hidden');$('#rankText')?.classList.add('hidden');const asc=[...groups].sort((a,b)=>a.ep-b.ep);await sleep(180);for(let i=0;i<asc.length;i++){const g=asc[i];stack.prepend(renderGroup(g,n,true));await animateScore($('#score'),total,total+g.ep,Math.max(210,360-i*4));total+=g.ep;await sleep(i<3?250:170)}setHeader(score);$('#shareButton')?.classList.remove('hidden');$('#rollActions')?.classList.remove('single')}else{for(const g of [...groups].sort((a,b)=>b.ep-a.ep))stack.appendChild(renderGroup(g,n,false));$('#score').textContent=fmt(score);setHeader(score)}currentResult={n,row,groups,score,rarity};return currentResult}
function randomNumber(){const c=globalThis.crypto;if(!c?.getRandomValues)throw new Error('Secure browser randomness is unavailable. Use a modern browser with Web Crypto enabled.');const a=new Uint32Array(1),range=0x100000000,limit=range-(range%U);do c.getRandomValues(a);while(a[0]>=limit);return a[0]%U}
async function rollNumber(n){if(busy)return;setBusy(true);clearResult();$('#dateLine').textContent='RANDOM';$('#status').textContent='';const dataPromise=Promise.all([loadCatalog(),getNumber(n)]);try{await slowNumber(n);const[,row]=await dataPromise;await revealResult(n,row,true)}catch(e){console.error(e);$('#status').textContent=e.message||'Could not load this roll.'}finally{setBusy(false)}}
async function exploreNumber(n){if(!Number.isInteger(n)||n<0||n>=U){$('#status').textContent='Enter an integer from 0 to 999999.';return}setBusy(true);$('#status').textContent='Loading…';try{const[,row]=await Promise.all([loadCatalog(),getNumber(n)]);instantNumber(n);$('#exploreHero')?.classList.remove('hidden');await revealResult(n,row,false);$('#status').textContent='';history.replaceState(null,'',`explore.html?n=${n}`)}catch(e){console.error(e);$('#status').textContent=e.message||'Could not load this number.'}finally{setBusy(false)}}

const shareSquare={Common:'🟩',Uncommon:'🟨',Rare:'🟦',Epic:'🟪',Anomaly:'🟧',Mythic:'🟥'},numberSquare={Trash:'⬛',Common:'⬜',Uncommon:'🟩',Rare:'🟦',Epic:'🟪',Anomaly:'🟧',Mythic:'🟥'};
function shareText(){if(!currentResult)return'';const{n,groups,score,rarity}=currentResult,top=[...groups].sort((a,b)=>b.ep-a.ep).slice(0,3).map(g=>`${shareSquare[g.rarity]||'⬜'} ${g.emoji} ${g.rep.oeis?`OEIS ${g.rep.oeis}`:g.name}`),more=groups.length>3?`\n+${groups.length-3} more`:'';return`Math RNGdle 🎲 ${n}\n\n${numberSquare[rarity]||'⬜'} ${rarity.toUpperCase()} • ${exactPercentile(score)}\n\n${top.join('\n')}${more}\n\n${fmt(score)} EP\nhttps://cybcatppuccino.github.io/MathRNGdle/index.html`}
async function copyShare(){const text=shareText();if(!text)return;try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}showToast('Result copied')}
function showToast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function initRoll(){$('#dateLine').textContent='RANDOM';$('#randomButton').addEventListener('click',()=>{try{rollNumber(randomNumber())}catch(e){console.error(e);$('#status').textContent=e.message||'Secure randomness is unavailable.'}});$('#shareButton').addEventListener('click',copyShare);const dlg=$('#rarityDialog');$('#rarityHelp').addEventListener('click',()=>dlg.showModal());$('#closeRarity').addEventListener('click',()=>dlg.close());dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()})}
function initExplore(){const form=$('#exploreForm'),input=$('#numberInput');form.addEventListener('submit',e=>{e.preventDefault();const s=input.value.trim();if(!/^\d+$/.test(s)){ $('#status').textContent='Enter an integer from 0 to 999999.';return}exploreNumber(Number(s))});const q=new URLSearchParams(location.search).get('n');if(q!==null&&/^\d+$/.test(q)&&Number(q)<U){input.value=q;exploreNumber(Number(q))}}
if(document.body.dataset.page==='explore')initExplore();else initRoll();
})();
