const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.dirname(path.dirname(__filename));
let src=fs.readFileSync(path.join(ROOT,'app.js'),'utf8');
const cut=src.lastIndexOf('  initEditor();');
if(cut<0)throw new Error('app initialization marker missing');
src=src.slice(0,cut)+`  globalThis.__TL_V9_TEST__={minimalTranslationLattice,gaussReducedBasis,finiteEquivalenceSig,periodicEquivalenceSig,liftedTileSig};\n})();\n`;
const dummy={};
const context={console,document:{getElementById:()=>dummy,documentElement:{}},window:{},location:{protocol:'http:'}};
context.globalThis=context;
vm.createContext(context);
vm.runInContext(src,context,{filename:'app.js'});
const T=context.__TL_V9_TEST__;
function assert(ok,msg){if(!ok)throw new Error(msg);}
function eq(a,b,msg){assert(JSON.stringify(a)===JSON.stringify(b),`${msg}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`);}
function P(cells){return {cells,rawCells:cells};}

// Vertical dominoes: quotient occupancy alone would falsely claim a y=1 symmetry.
const vertical={kind:'periodic',w:4,h:2,lattice:{a:4,b:0,c:2},placements:[0,1,2,3].map(x=>P([[x,0],[x,1]]))};
let L=T.minimalTranslationLattice(vertical);
eq([L.a,L.b,L.c],[1,0,2],'vertical domino minimal lattice');

const horizontal={kind:'periodic',w:4,h:2,lattice:{a:4,b:0,c:2},placements:[P([[0,0],[1,0]]),P([[2,0],[3,0]]),P([[0,1],[1,1]]),P([[2,1],[3,1]])]};
L=T.minimalTranslationLattice(horizontal);
eq([L.a,L.b,L.c],[2,0,1],'horizontal domino minimal lattice');

// Brick/staggered rows: smallest lattice is generated by (2,0) and (1,1).
const brick={kind:'periodic',w:4,h:2,lattice:{a:4,b:0,c:2},placements:[P([[0,0],[1,0]]),P([[2,0],[3,0]]),P([[1,1],[2,1]]),P([[3,1],[4,1]])]};
L=T.minimalTranslationLattice(brick);
eq([L.a,L.b,L.c],[2,1,1],'staggered domino minimal lattice');
const B=T.gaussReducedBasis(L);
assert(Math.abs(B[0][0]*B[1][1]-B[0][1]*B[1][0])===2,'Gauss basis determinant');

const finiteA={placements:[P([[0,0],[1,0],[0,1]]),P([[3,0],[3,1],[4,1]])]};
const finiteB={placements:[P([[10,7],[10,8],[9,7]]),P([[10,10],[9,10],[9,11]])]}; // rotated/reflected + translated arrangement
assert(T.finiteEquivalenceSig(finiteA)===T.finiteEquivalenceSig(finiteB),'finite D4/translation equivalence');


const brickShift={kind:'periodic',w:4,h:2,lattice:{a:4,b:0,c:2},placements:brick.placements.map(p=>P(p.rawCells.map(([x,y])=>[x+1,y])))};
assert(T.periodicEquivalenceSig(brick)===T.periodicEquivalenceSig(brickShift),'periodic phase-translation equivalence');

const perA={kind:'periodic',w:1,h:2,lattice:{a:1,b:0,c:2},placements:[P([[0,0],[0,1]])]};
const perB={kind:'periodic',w:2,h:1,lattice:{a:2,b:0,c:1},placements:[P([[0,0],[1,0]])]};
assert(T.periodicEquivalenceSig(perA)===T.periodicEquivalenceSig(perB),'periodic quarter-turn equivalence');

console.log('OK: v9 minimal lattice + Gauss basis + D4/translation equivalence post-processing');
