const fs = require('fs');
const script = fs.readFileSync('ries-script.js','utf8');
if (/irreducible algebraic:/.test(script)) throw new Error('visible algebraic labels must not claim irreducibility');
const callMatches = [...script.matchAll(/isIrreducibleIntegerPoly\s*\(/g)].length;
if (callMatches !== 1) throw new Error('isIrreducibleIntegerPoly should remain only as an unused definition, calls found: '+callMatches);
if (!/function scaledPowersForAlgebraic\(/.test(script)) throw new Error('missing scaledPowersForAlgebraic cache helper');
if (!/parsed\.isComplex\s*\?\s*complexScaledPowers[\s\S]*decimalScaledPowers/.test(script)) throw new Error('real decimal path should prefer decimalScaledPowers, reserving complexScaledPowers for complex input');
if ((script.match(/scaledPowersForAlgebraic\(settings, parsed, val, deg, usePrec, powerCache\)/g)||[]).length < 2) throw new Error('LLL construction should use cached scaled powers in both sync and async relation candidates');
if ((script.match(/scaledPowersForAlgebraic\(settings, parsed, val, pd, requestedPrec, powerCache\)/g)||[]).length < 2) throw new Error('verification should use cached scaled powers in both sync and async relation candidates');
console.log('PASS RIES v11.2.3 algebraic no-irreducible decimal-cache regression');
