const fs = require('fs');
const vm = require('vm');
function fakeEl(id){return {id,value:'',checked:true,hidden:false,disabled:false,dataset:{},style:{setProperty(){}},className:'',textContent:'',innerHTML:'',open:false,classList:{contains(){return false},add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},appendChild(child){return child},prepend(){},insertAdjacentElement(){},querySelector(){return fakeEl('q')},querySelectorAll(){return []},getContext(){return {}},closest(){return null},getAttribute(){return ''}};}
const ids=['resultBody','resultTools','resultToolsMeta','sortConfidenceBtn','sortDiscoveryBtn','hpPanel','hpContent','numberTools','numberToolsContent','status','paramToggle','parametersPanel','stopBtn','continueBtn','runBtn','target','onlySyms','neverSyms','digits','restrictMode','tolerance','maxAbs','level','shortEffort','limit','doEq','doAlg','doLog','allowExternalFactorization','logHeight','logPrecision','logSlack','algHeight','algDegree','algPrecision','algResidualPower','defaultLogBasis','extraLogBasis'];
const els={}; ids.forEach(id=>els[id]=fakeEl(id));
els.digits.value='0123456789'; els.restrictMode.value='none'; els.maxAbs.value='1e9'; els.level.value='4'; els.shortEffort.value='3'; els.limit.value='10'; els.doEq.checked=true; els.doAlg.checked=false; els.doLog.checked=false; els.logHeight.value='400';
const sandbox={console, performance:{now:()=>Date.now()}, setTimeout, clearTimeout, requestAnimationFrame:(cb)=>setTimeout(()=>cb(Date.now()),0), cancelAnimationFrame(){}, MathJax:null};
sandbox.window=sandbox; sandbox.navigator={clipboard:null, scheduling:{isInputPending:()=>false}};
sandbox.document={getElementById:id=>els[id]||null, querySelectorAll:()=>[], querySelector:()=>fakeEl('qs'), createElement:tag=>fakeEl(tag), addEventListener(){}, body:{contains:()=>true, prepend(){}}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('assets/decimal.js','utf8'), sandbox);
vm.runInContext(fs.readFileSync('assets/constantdb300.js','utf8'), sandbox);
vm.runInContext(fs.readFileSync('ries-script.js','utf8'), sandbox);
function settingsFor(v, level=4){ els.target.value=String(v); els.level.value=String(level); return sandbox.readSettings(); }
const C=sandbox.__RIES_CONSTDB_TEST__;
const L=sandbox.__RIES_LOG_TEST__;
const E=sandbox.__RIES_EQUATION_TEST__;
let s=settingsFor('2.386110381167886',4);
let t=Date.now();
let rows=C.constantDbRows(s);
let logPiPoly=rows.find(r => /c = π/.test(r.valueHtml||'') && /low-degree polynomial relation in transformed value,1,c,c\^2/.test(r.constantDbCategory||''));
if(!logPiPoly) throw new Error('missing constant DB log-polynomial hit: '+rows.map(r=>r.candidate+' | '+r.constantDbCategory).join('\n'));
if(!/exp\(\(−12 \+ 4·c \+ c\^2\)\/12\)/.test(logPiPoly.candidate||'')) throw new Error('bad candidate text: '+logPiPoly.candidate);
if(!/^x \\approx \\exp\\left\(\\frac\{-12 \+ 4\\,c \+ c\^\{2\}\}\{12\}\\right\)$/.test(logPiPoly.latex||'')) throw new Error('bad constant DB latex: '+JSON.stringify(logPiPoly.latex));
if(Date.now()-t > 7000) throw new Error('constant DB targeted log-polynomial pass is too slow');
const s15=settingsFor('1.23456789012345',4);
const s8=settingsFor('1.2345678',4);
if(C.typedInputPrecisionForDouble(s15)!==15) throw new Error('15-digit input should remain 15 digits');
if(C.typedInputPrecisionForDouble(s8)!==8) throw new Error('sub-16 digit input precision should be unchanged');
const rel={coeff:[3n,0n,-2n,0n,12n], rhs:(2/3)*Math.log(2)-4*Math.log(5), err:1e-16, height:12n};
const ll=L.logProductLatex(rel,L.logConstants);
if(ll !== '2^{2/3}\\,5^{-4}') throw new Error('bad log|c| product latex: '+JSON.stringify(ll));
const eqSettings=settingsFor(Math.sqrt(5),4);
const eqRows=E.equationSearch(E.generateConstants(eqSettings), eqSettings);
const eq=eqRows.find(r => r.latex && /x/.test(r.latex));
if(!eq) throw new Error('equationSearch did not produce latex rows');
if(/x approx|[^\\]approx/.test(eq.latex)) throw new Error('bad RIES equation latex: '+JSON.stringify(eq.latex));
if(/[\f\r\b\x07]/.test(eq.latex)) throw new Error('control escape in RIES equation latex: '+JSON.stringify(eq.latex));
console.log('PASS RIES v11.1.1 decimal log-polynomial, log|c| latex, RIES equation latex, and precision cap tests');
process.exit(0);
