const fs = require('fs');
const vm = require('vm');
const path = require('path');
const root = path.resolve(__dirname, '..');
const assetPath = path.join(root, 'assets', 'ries-harddb-v11_4_1-filtered.js');
const statsPath = path.join(root, 'assets', 'ries-harddb-v11_4_1-filtered-stats.json');
const size = fs.statSync(assetPath).size;
if (size > 10_000_000) throw new Error(`filtered direct hard DB asset exceeds decimal 10MB: ${size}`);
const sandbox = {window:{}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(assetPath, 'utf8'), sandbox);
const d = sandbox.window.RIES_HARDDB_V114_DIRECT;
const stats = JSON.parse(fs.readFileSync(statsPath, 'utf8'));
if (!d) throw new Error('direct hard DB object not installed on window');
if (d.rows < 79000 || d.rows > 81000 || d.rows !== stats.rows) throw new Error(`row mismatch: ${d.rows}`);
if (d.valuesB64.length !== Math.ceil(stats.valueBytes / 3) * 4) throw new Error('values b64 length mismatch');
if (d.rowMapB64.length !== Math.ceil(stats.rowMapBytes / 3) * 4) throw new Error('row map b64 length mismatch');
if (d.origRowsB64.length !== Math.ceil(stats.origRowBytes / 3) * 4) throw new Error('original-row b64 length mismatch');
if (d.paramB64.length !== Math.ceil(stats.paramBytes / 3) * 4) throw new Error('param b64 length mismatch');
if (d.dict.split('\t').length !== stats.dictionaryEntries) throw new Error('dictionary length mismatch');
console.log(`OK filtered direct harddb asset: ${d.rows} rows, ${size} bytes, no fetch/gzip required`);
