const fs = require('fs');
const html = fs.readFileSync('ries.html','utf8');
if(!html.includes('RIES <em>v11.6.4</em>')) throw new Error('ries.html visible version should be v11.6.4');
if(!html.includes('ries-script.js?v=11.6.4')) throw new Error('ries-script cache tag should be v11.6.4');
if(/<script[^>]+ries-harddb-v11_6-level[45]\.js/i.test(html)) throw new Error('harddb chunks must be lazy-loaded');
if(/<script[^>]+ries-hypdata-v11_5_2-level[456]\.js/i.test(html)) throw new Error('hypdata chunks must remain lazy-loaded');
for(const f of ['assets/ries-harddb-v11_6-level4.js','assets/ries-harddb-v11_6-level5.js','assets/ries-harddb-v11_6-stats.json']) if(!fs.existsSync(f)) throw new Error(`${f} missing`);
if(!fs.existsSync('changelog/RIES_v11.6.4_CHANGELOG.md')) throw new Error('v11.6.4 changelog missing');
const stats = JSON.parse(fs.readFileSync('assets/ries-harddb-v11_6-stats.json','utf8'));
if(stats.level4Rows !== 15986 || stats.level5AdditionalRows !== 63946) throw new Error('harddb split row counts changed unexpectedly');
console.log('PASS RIES v11.6.4 packaging smoke test');
