const fs = require('fs');
const vm = require('vm');
function fakeEl(id){return {id,value:'',checked:true,hidden:false,disabled:false,dataset:{},style:{setProperty(){}},className:'',textContent:'',innerHTML:'',open:false,classList:{contains(){return false},add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},appendChild(child){return child},prepend(){},insertAdjacentElement(){},querySelector(){return fakeEl('q')},querySelectorAll(){return []},getContext(){return {}},closest(){return null},getAttribute(){return ''}};}
const ids=['resultBody','resultTools','resultToolsMeta','sortConfidenceBtn','sortDiscoveryBtn','hpPanel','hpContent','numberTools','numberToolsContent','status','paramToggle','parametersPanel','stopBtn','continueBtn','runBtn','target','onlySyms','neverSyms','digits','restrictMode','tolerance','maxAbs','level','shortEffort','limit','doEq','doAlg','doLog','allowExternalFactorization','logHeight','logPrecision','logSlack','algHeight','algDegree','algPrecision','algResidualPower','defaultLogBasis','extraLogBasis'];
const els={}; ids.forEach(id=>els[id]=fakeEl(id));
els.digits.value='0123456789'; els.restrictMode.value='none'; els.maxAbs.value='1e9'; els.level.value='4'; els.shortEffort.value='3'; els.limit.value='10'; els.doEq.checked=true; els.doAlg.checked=false; els.doLog.checked=false; els.logHeight.value='400';
const sandbox={console, performance:{now:()=>Date.now()}, setTimeout, clearTimeout, requestAnimationFrame:(cb)=>setTimeout(()=>cb(Date.now()),0), cancelAnimationFrame(){}, MathJax:null};
sandbox.window=sandbox; sandbox.navigator={clipboard:null, scheduling:{isInputPending:()=>false}};
sandbox.document={getElementById:id=>els[id]||null, querySelectorAll:()=>[], querySelector:()=>fakeEl('qs'), createElement:tag=>fakeEl(tag), addEventListener(){}, body:{contains:()=>true, prepend(){}}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('assets/decimal.js','utf8'), sandbox);
vm.runInContext(fs.readFileSync('assets/constantdb300.js','utf8'), sandbox);
const source=fs.readFileSync('ries-script.js','utf8');
if(source.includes('for(const row of constDbPriorityTransformedPolynomialRows')) throw new Error('priority transformed mini-scan is still called');
vm.runInContext(source, sandbox);
const C=sandbox.__RIES_CONSTDB_TEST__;
els.target.value='2.386110381167886';
const settings=sandbox.readSettings();
const order=C.constDbTransformRows(settings).map(v=>v.kind).slice(0,5).join(',');
if(order !== 'pow1,logabs,exp,powm1,pow2') throw new Error('bad transform order: '+order);
if(C.constantDbBudgetMs(4,16)!==6000) throw new Error('level-4 constant DB budget should be 6000ms after 1.2x multiplier');
const rows=C.constantDbRows(settings);
const hit=rows.find(r => /exp\(\(−12 \+ 4·c \+ c\^2\)\/12\)/.test(r.candidate||'') && /c = π/.test(r.valueHtml||''));
if(!hit) throw new Error('missing exp((-12+4π+π²)/12) constant DB hit: '+rows.map(r=>r.candidate+' | '+r.constantDbCategory).join('\n'));
console.log('PASS RIES v11.1.2 constant DB transform order, 1.2x budget, and log-polynomial hit');
